### ISSUE TITLE
Why was vscode-iis added?

### ISSUE THREAD

**Issue by ilharp** [lextudio/vscode-restructuredtext-pack#1]
Just now I opened VSCode and found [vscode-iis](https://github.com/jexuswebserver/vscode-iis) installed. Looks like this extension pack is the cause, you just added vscode-iis in [this commit](https://github.com/lextudio/vscode-restructuredtext-pack/commit/b137adc4b0b139107cd040eb4aa09056f5dd8514).

Is there any correlation between reStructuredText and IIS?

In the `README.md` what I see is:

https://github.com/lextudio/vscode-restructuredtext-pack/blob/b137adc4b0b139107cd040eb4aa09056f5dd8514/README.md?plain=1#L5

Is vscode-iis an extension that can help write or preview reStructuredText files?

**Comment by lextm** [comment]
If you are on Windows, the IIS extension allows you to quickly host the generated pages on IIS/IIS Express. The steps will be documented soon.

**Comment by lextm** [comment]
Updated the README file to include more on the IIS extension.
